import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url)).replace(/\/$/,'');
const base=process.argv[2]||process.env.EQAO_TEST_URL||'http://127.0.0.1:8766/';
const boardBase=new URL('?view=boards&grade=3&language=en&type=all&year=2026&subject=0&focus=66052&pins=66052,66095',base).href;
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});
const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{document.modelContext={registerTool(t){window.eqaoTool=t;}}});
await page.goto(boardBase);await page.locator('#board-table tbody tr').first().waitFor();
await page.screenshot({path:root+'/tests/desktop.png',fullPage:true});
await page.screenshot({path:root+'/tests/editorial-preview.png'});
assert.equal(await page.locator('#board-count').textContent(),'60 boards · English-language');
assert.equal(await page.locator('.card.primary .stat').textContent(),'75%');
assert.match(await page.locator('.trend-panel h2').textContent(),/Reading is up 2 points since 2021–22/);
assert.equal(await page.locator('#trend .end-label').count(),3);
assert.match(await page.locator('#trend .chart-annotation').textContent(),/2023–24 · 71%/);
await page.locator('#trend circle').first().focus();
await page.keyboard.press('Enter');
assert.match(await page.locator('#trend-readout').textContent(),/Ontario · 2021–22 · 73%/);
await page.locator('#year').selectOption('2024');
assert.match(await page.locator('.trend-panel h2').textContent(),/Reading is down 2 points/);
await page.locator('#year').selectOption('2022');
assert.match(await page.locator('.trend-panel h2').textContent(),/73% met the reading standard in 2021–22/);
await page.locator('#year').selectOption('2026');
// Close values must remain distinguishable with the maximum comparison count.
for(let j=0;j<2;j++){
  const id=await page.locator('#add-board option').nth(1).getAttribute('value');
  await page.locator('#add-board').selectOption(id);
}
assert.equal(await page.locator('#trend .end-label').count(),5);
const labelBounds=await page.locator('#trend .end-label').evaluateAll(labels=>labels.map(l=>{const r=l.getBoundingClientRect();return {top:r.top,bottom:r.bottom}}).sort((a,b)=>a.top-b.top));
for(let j=1;j<labelBounds.length;j++)assert.ok(labelBounds[j].top>=labelBounds[j-1].bottom,'Direct series labels must not overlap');
await page.goto(boardBase);await page.locator('#board-table tbody tr').first().waitFor();
await page.locator('[data-grade="6"]').click();
assert.equal(await page.locator('.card.primary .stat').textContent(),'86%');
await page.locator('[data-subject="2"]').click();
await page.locator('#language').selectOption('fr');
assert.equal(await page.locator('#board-count').textContent(),'12 boards · French-language');
await page.locator('#boardType').selectOption('Catholic');
assert.equal(await page.locator('#board-count').textContent(),'8 boards · French-language');
await page.locator('#year').selectOption('2022');assert.equal(await page.locator('#notice').isVisible(),true);
await page.locator('#language').selectOption('en');await page.locator('#boardType').selectOption('all');await page.locator('#year').selectOption('2026');
await page.locator('#board-search').fill('Toronto DSB');assert.equal(await page.locator('#board-table tbody tr').count(),1);
const downloadWait=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadWait;await download.saveAs(root+'/tests/filtered-export.csv');
assert.match(await fs.readFile(root+'/tests/filtered-export.csv','utf8'),/Toronto DSB/);
await page.locator('#board-search').fill('there is no such school board');assert.match(await page.locator('#board-table').textContent(),/No boards match/);
await page.locator('#board-search').fill('');await page.locator('[data-sort="2"]').click();
const tool=await page.evaluate(()=>({valid:window.eqaoTool.execute({}).rows.length,invalid:(()=>{try{window.eqaoTool.execute({bad:true});return false}catch{return true}})()}));assert.equal(tool.valid,60);assert.equal(tool.invalid,true);
await page.locator('[data-view="schools"]').click();await page.locator('#school-table tbody tr').first().waitFor();await page.locator('#school-search').fill('Woodbridge');
await page.locator('[data-school]').first().click();await page.locator('#school-trend svg').waitFor();await page.screenshot({path:root+'/tests/school-detail.png'});await page.locator('.dialog-close').click();
await page.locator('[data-view="archive"]').click();await page.locator('#archive-summary table').waitFor();assert.match(await page.locator('#notice').textContent(),/unweighted/);await page.locator('#year').selectOption('2018');await page.locator('#school-table').waitFor();await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:root+'/tests/archive.png'});
await page.locator('[data-view="sources"]').click();assert.equal(await page.locator('.source-list li').count(),31);await page.screenshot({path:root+'/tests/sources.png'});
await page.goto(boardBase);await page.locator('#board-table tbody tr').first().waitFor();
await page.setViewportSize({width:1024,height:1000});await page.waitForTimeout(250);await page.screenshot({path:root+'/tests/tablet.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Tablet page should not overflow horizontally');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);await page.screenshot({path:root+'/tests/mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile page should not overflow horizontally');
assert.equal(await page.locator('#trend .chart-key-item').count(),3);
assert.equal(await page.locator('#trend .end-label').count(),0);
await page.locator('[data-view="sources"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Sources page should fit mobile');
const sourceLinks=await page.locator('.source-list>li>a').evaluateAll(as=>as.map(a=>a.href));
for(const url of sourceLinks){const r=await page.request.head(url);assert.equal(r.status(),200,url);}
await page.locator('[data-view="boards"]').click();
await page.locator('[data-grade="6"]').click();await page.locator('[data-subject="2"]').click();
await page.setViewportSize({width:320,height:760});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'320px page should not overflow horizontally');
await page.setViewportSize({width:1440,height:1060});await page.locator('#boardType').selectOption('Other authority');assert.match(await page.locator('#board-count').textContent(),/boards/);
assert.deepEqual(errors,[]);
const report={passed:true,url:base,desktop:'1440x1060',mobile:['390x844','320x760'],checks:['source-backed headline values','filter-aware findings and exact low-point annotation','keyboard-accessible chart values','five direct series labels without overlap','responsive chart key','grade and subject switching','English/French and board-type filters','2021-22 caveat','search and empty state','filtered CSV download','sort','read-only agent tool valid and invalid inputs','school history dialog','historical archive','31 source links return HTTP 200','no mobile page overflow including Sources','no uncaught browser errors']};
await fs.writeFile(root+'/tests/browser-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
await browser.close();
