/* Execute the actual prototype event handlers against a DOM stub. This does
   not simulate browser rendering, modal focus behavior or pointer input. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
vm.runInThisContext(fs.readFileSync('site/saved-model.js','utf8'));const {SavedSchools}=globalThis;
const index=JSON.parse(fs.readFileSync('site/data/schools-index.json'));
class Node {
  constructor(selector,doc){this.selector=selector;this.doc=doc;this.dataset={};this.attributes={};this.listeners={};this.value='';this.hidden=false;this.open=false;this.isConnected=true;this.scrollTop=0;this.clientWidth=390;this.classList={add(){},remove(){},toggle(){}};}
  setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}append(...nodes){nodes.forEach(n=>n.parent=this);}before(){}
  insertAdjacentHTML(){}querySelector(s){return this.doc.querySelector(s);}querySelectorAll(s){if(s==='[data-temp-grade]'||s==='[data-temp-subject]'){const grade=s.includes('grade');return (grade?[3,6]:[0,1,2]).map(value=>{const node=this.doc.querySelector(s+value);node.dataset[grade?'tempGrade':'tempSubject']=String(value);return node;});}return [];}
  addEventListener(type,fn){this.listeners[type]=fn;}focus(){this.doc.activeElement=this;}scrollIntoView(){}
  showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}
  getBoundingClientRect(){return {left:810,right:1280,top:0,bottom:900};}
}
function setup(saved,search='',options={}){
  const map=new Map(),doc={created:[],activeElement:null,querySelector(s){if(!map.has(s))map.set(s,new Node(s,doc));return map.get(s);},querySelectorAll(){return [];},createElement(s){const node=new Node(s,doc);this.created.push(node);return node;},addEventListener(type,fn){this[type]=fn;}};
  doc.body=new Node('body',doc);doc.activeElement=doc.querySelector('initial-focus');
  const storage=new Map(options.storage||[]),sessions=new Map(options.sessions||[]);if(saved!==undefined)storage.set('eqao-saved-schools-v1',JSON.stringify(saved));
  const globals={window:{listeners:{},addEventListener(type,fn){this.listeners[type]=fn;}},document:doc,SavedSchools,URL,URLSearchParams,sessionStorage:{getItem:k=>sessions.get(k)||null,setItem:(k,v)=>sessions.set(k,v),removeItem:k=>sessions.delete(k)},location:{search,pathname:'/eqao-explorer/',origin:'https://example.test'},history:{state:null,pushState(snapshot,title,url){this.state=snapshot;globals.lastHistory={snapshot,url};globals.location.search=new URL(url,'https://example.test').search;},replaceState(snapshot,title,url){this.state=snapshot;globals.lastHistory={snapshot,url};globals.location.search=new URL(url,'https://example.test').search;}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},schoolIndex:index,schoolInfo:id=>index.find(s=>s.id===id),board:()=>({type:'Public'}),getSchoolIndex:async()=>index,esc:s=>String(s??''),languageLabel:l=>l==='en'?'English-language':'French-language',state:{pins:[],view:options.view||'myschool',school:options.mySchool||'013200',comparisons:['031011'],year:2026,grade:3,language:'en',type:'all',subject:0},ui:{schoolDetails:new Set()},renderToken:0,homeContext:null,pushNavigation:false,updateSchoolPicker(){},render(){this;globals.renderToken++;globals.homeContext={meta:{id:globals.state.school}};globals.capturedRender={...globals.state};vm.runInContext('refreshUrl()',globals);},setView(view){globals.state.view=view},MutationObserver:class{observe(){}},setTimeout(fn,ms){if(ms===50)queueMicrotask(fn);return 1;},clearTimeout(){}};
  if(!search)globals.location.search='?view='+(options.view||'myschool')+'&school='+(options.mySchool||'013200');if(!storage.has('eqao-my-school-v1'))storage.set('eqao-my-school-v1',JSON.stringify({school:options.mySchool||'013200',comparisons:['031011'],grade:3,year:2026}));globals.$=s=>doc.querySelector(s);globals.data=JSON.parse(fs.readFileSync('site/data/core.json'));globals.subjects=['Reading','Writing','Mathematics'];globals.yearLabel=y=>`${y-1}–${String(y).slice(2)}`;globals.pct=v=>v==null?'—':v+'%';globals.number=v=>String(v);globals.rawLabel=(r,i)=>globals.pct(r?.values?.[i]);globals.difference=(a,b)=>a==null||b==null?null:a-b;globals.delta=v=>v==null?'—':`${v>0?'+':''}${Number(v.toFixed(1))} pp`;globals.getSchools=async(y,g)=>JSON.parse(fs.readFileSync(`site/data/schools-${y}-${g}.json`));globals.window.scrollY=140;globals.window.scrollTo=()=>{};vm.createContext(globals);const app=fs.readFileSync('site/app.js','utf8');vm.runInContext(app.slice(app.indexOf('function refreshUrl(){'),app.indexOf('function restoreUrl(')),globals);globals.defaultState=vm.runInContext(app.match(/^const defaultState=(.+);$/m)[1],globals);vm.runInContext(app.slice(app.indexOf('function restoreUrl('),app.indexOf('restoreUrl();')),globals);vm.runInContext('restoreUrl();refreshUrl()',globals);vm.runInContext(app.slice(app.indexOf('function drawTrend('),app.indexOf('function renderFocus(')),globals);vm.runInContext(fs.readFileSync('site/saved-comparison.js','utf8'),globals);vm.runInContext(fs.readFileSync('site/saved.js','utf8'),globals);
  return {globals,doc,map,storage,sessions,async ready(){await globals.window.savedCompareReady;for(let i=0;i<10;i++)await Promise.resolve();return this;},node(s){return doc.querySelector(s);},dialog(){return doc.body;}};
}
(async()=>{
  const seed=['013200','039594','002151','019445','031011','009172','004499'];
  const h=await setup({ids:seed,selected:seed.slice(0,3)}).ready(),m=h.globals.window.savedSchools;
  assert.deepEqual(m.model.ids,seed);assert.deepEqual(m.model.selected,seed.slice(0,3));
  const opener=h.doc.activeElement;m.open();const dialog=h.doc.created.find(n=>n.id==='saved-dialog');const toast=h.doc.created.find(n=>n.className==='saved-toast');
  dialog.listeners.click({target:{closest:s=>s==='[data-saved-remove]'?{dataset:{savedRemove:seed[1]}}:null}});assert(!m.model.ids.includes(seed[1]));assert(!m.model.selected.includes(seed[1]));assert.equal(toast.parent,dialog);toast.onclick({target:{closest:s=>s==='#saved-undo'?{}:null}});assert(m.model.ids.includes(seed[1]));assert(m.model.selected.includes(seed[1]));assert.equal(m.model.ids[1],seed[1]);
  m.model.selected=seed.slice(0,5);m.open();dialog.listeners.change({target:{dataset:{savedSelect:seed[5]}}});assert.equal(m.model.selected.length,5);assert(h.node('#saved-feedback').textContent.includes('up to five'));dialog.listeners.change({target:{dataset:{savedSelect:seed[2]}}});dialog.listeners.change({target:{dataset:{savedSelect:seed[5]}}});assert(m.model.selected.includes(seed[5]));assert.equal(m.model.selected.length,5);m.model.selected=seed.slice(0,3);m.open();m.close();h.doc.activeElement=opener;m.open();
  m.close();assert.equal(h.doc.activeElement,opener);assert.deepEqual(m.model.selected,seed.slice(0,3));m.open();
  const before=JSON.parse(JSON.stringify(h.globals.state));const initialMySchoolStorage=h.storage.get('eqao-my-school-v1');await h.node('#saved-compare').onclick();assert.deepEqual(JSON.parse(JSON.stringify(h.globals.state)),before);assert.equal(h.globals.window.savedCompareScreen.context.reference,'');assert.deepEqual([...h.globals.window.savedCompareScreen.context.schools],seed.slice(0,3));const route=new URL(h.globals.lastHistory.url,'https://example.test');assert.equal(route.searchParams.get('view'),'myschool');assert.equal(route.searchParams.get('school'),seed[0]);assert.equal(route.searchParams.get('compare'),'031011');assert.equal(route.searchParams.get('comparison'),seed.slice(0,3).join(','));assert.equal(h.node('#main').hidden,true);assert.equal(h.storage.get('eqao-my-school-v1'),initialMySchoolStorage);assert.equal((h.node('#temp-school-chart').innerHTML.match(/class="trend-line"/g)||[]).length,3);assert(!h.node('#temp-school-chart').innerHTML.includes('Selected school'));
  h.node('#temp-reference').onchange({target:{value:seed[2]}});assert.equal(h.globals.window.savedCompareScreen.context.reference,seed[2]);assert.deepEqual(JSON.parse(JSON.stringify(h.globals.state)),before);assert(h.node('#temp-difference-results').innerHTML.includes('Reference'));assert.equal(h.node('#temp-reference').attributes?.['aria-current'],undefined);m.open();m.close();assert.deepEqual(JSON.parse(JSON.stringify(h.globals.state)),before);
  const currentSearch=h.globals.location.search;const reload=await setup({ids:seed,selected:seed.slice(0,3)},currentSearch,{storage:[...h.storage],sessions:[...h.sessions]}).ready();assert.equal(reload.globals.window.savedCompareScreen.context.reference,seed[2]);assert.equal(reload.globals.state.school,seed[0]);assert.deepEqual([...reload.globals.state.comparisons],['031011']);reload.globals.window.savedCompareScreen.back();assert.equal(reload.globals.state.school,seed[0]);assert.equal(reload.node('#main').hidden,false);assert(!reload.globals.location.search.includes('comparison='));
  h.globals.window.savedCompareScreen.back();assert.deepEqual(JSON.parse(JSON.stringify(h.globals.state)),before);assert.equal(h.node('#main').hidden,false);assert.equal(h.globals.window.savedCompareScreen.context,null);
  const outside=await setup({ids:seed,selected:seed.slice(0,3)},'',{mySchool:seed[6],view:'schools'}).ready();const outsideBefore=JSON.parse(JSON.stringify(outside.globals.state));await outside.node('#saved-compare').onclick();assert.deepEqual(JSON.parse(JSON.stringify(outside.globals.state)),outsideBefore);assert(!outside.globals.window.savedCompareScreen.context.schools.includes(seed[6]));outside.node('#temp-reference').onchange({target:{value:seed[1]}});assert.equal(outside.globals.state.school,seed[6]);const outsideReload=await setup({ids:seed,selected:seed.slice(0,3)},outside.globals.location.search,{storage:[...outside.storage],sessions:[...outside.sessions]}).ready();assert.equal(outsideReload.globals.state.school,seed[6]);assert.equal(outsideReload.globals.window.savedCompareScreen.context.reference,seed[1]);outsideReload.globals.window.savedCompareScreen.back();assert.equal(outsideReload.globals.state.school,seed[6]);assert.equal(outsideReload.globals.state.view,'schools');outside.globals.window.savedCompareScreen.back();assert.deepEqual(JSON.parse(JSON.stringify(outside.globals.state)),outsideBefore);assert.equal(outside.globals.state.view,'schools');
  const later=await setup({ids:seed,selected:[seed[0],seed[1],seed[4]]},'',{mySchool:seed[4]}).ready();await later.node('#saved-compare').onclick();assert.equal(later.globals.state.school,seed[4]);assert.equal(later.globals.window.savedCompareScreen.context.reference,'');later.node('#temp-reference').onchange({target:{value:seed[0]}});assert.equal(later.globals.state.school,seed[4]);const pane=later.doc.created.find(n=>n.id==='saved-comparison-main');await pane.querySelectorAll('[data-temp-grade]')[1].onclick();assert.equal(later.globals.window.savedCompareScreen.context.grade,6);assert.equal(later.globals.state.grade,3);await later.node('#temp-comparison-year').onchange({target:{value:'2025'}});assert.equal(later.globals.window.savedCompareScreen.context.year,2025);assert.equal(later.globals.state.year,2026);
  m.model.selected=seed.slice(0,5);m.open();await h.node('#saved-compare').onclick();assert.equal(h.globals.window.savedCompareScreen.context.schools.length,5);assert.equal((h.node('#temp-school-chart').innerHTML.match(/class="trend-line"/g)||[]).length,5);assert.deepEqual(JSON.parse(JSON.stringify(h.globals.state)),before);h.globals.window.savedCompareScreen.back();
  const nav=await setup({ids:seed,selected:seed.slice(0,3)},'',{mySchool:seed[6],view:'schools'}).ready();await nav.node('#saved-compare').onclick();nav.node('#temp-reference').onchange({target:{value:seed[2]}});const forwardURL=nav.globals.location.search,returnState=JSON.parse(JSON.stringify(nav.globals.window.savedCompareScreen.context.returnContext.state)),returnURL=nav.globals.window.savedCompareScreen.context.returnContext.url;nav.globals.location.search=new URL(returnURL,'https://example.test').search;Object.assign(nav.globals.state,returnState);await nav.globals.window.listeners.popstate();assert.equal(nav.node('#main').hidden,false);assert.equal(nav.globals.window.savedCompareScreen.context,null);assert.equal(nav.globals.state.school,seed[6]);nav.globals.location.search=forwardURL;await nav.globals.window.listeners.popstate();assert.equal(nav.node('#main').hidden,true);assert.equal(nav.globals.window.savedCompareScreen.context.reference,seed[2]);assert.equal(nav.globals.state.school,seed[6]);nav.globals.window.savedCompareScreen.back();assert.equal(nav.globals.state.view,'schools');
  h.node('#saved-clear-selection').onclick();assert.equal(m.model.selected.length,0);assert.equal(h.node('#saved-compare').disabled,true);
  const payload=JSON.parse(h.storage.get('eqao-saved-schools-v1'));assert.equal(payload.selected.length,0);assert.deepEqual(payload.ids,seed);
  const fresh=await setup(payload).ready();assert.deepEqual(fresh.globals.window.savedSchools.model.ids,seed);assert.deepEqual(fresh.globals.window.savedSchools.model.selected,[]);
  const malformed=await setup({ids:'bad data',selected:'bad data'}).ready();assert.equal(malformed.globals.window.savedSchools.model.ids.length,0);
  h.globals.window.listeners.storage({key:'eqao-saved-schools-v1',newValue:JSON.stringify({ids:seed.slice(0,2),selected:[seed[1]]})});assert.deepEqual(m.model.ids,seed.slice(0,2));assert.deepEqual(m.model.selected,[seed[1]]);
  h.globals.window.listeners.storage({key:'eqao-my-school-v1',newValue:JSON.stringify({ids:[],selected:[]})});assert.equal(m.model.ids.length,2);
  h.globals.window.listeners.storage({key:'eqao-saved-schools-v1',newValue:null});assert.equal(m.model.ids.length,0);
  const empty=await setup(undefined).ready();assert.equal(empty.globals.window.savedSchools.model.ids.length,0);assert.equal(empty.node('#saved-compare').disabled,true);
  const ids=index.slice(0,101).map(s=>s.id),capacity=new SavedSchools();ids.slice(0,100).forEach(id=>assert.equal(capacity.save(id),'saved'));assert.equal(capacity.save(ids[100]),'full');assert.equal(capacity.save(ids[0]),'already');for(let i=0;i<20;i++){const removed=capacity.remove(ids[0]);assert(capacity.undo(removed));assert.equal(capacity.ids.length,100);assert.equal(new Set(capacity.ids).size,100);}
  const html=fs.readFileSync('site/index.html','utf8'),css=fs.readFileSync('site/saved.css','utf8'),stack=[],voidTags=new Set('area base br col embed hr img input link meta param source track wbr'.split(' '));for(const tag of html.matchAll(/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi)){const name=tag[1].toLowerCase();if(tag[0].startsWith('</'))assert.equal(stack.pop(),name,'HTML nesting');else if(!voidTags.has(name)&&!tag[0].endsWith('/>'))stack.push(name);}assert.equal(stack.length,0);assert(html.includes('width=device-width, initial-scale=1'));assert(css.includes('@media(max-width:760px)'));assert(css.includes('#saved-dialog{width:100%;border:0}'));assert(css.includes('.saved-footer{display:block;'));assert(css.includes('.temp-results-table thead{display:none}'));assert(css.includes('grid-template-columns:repeat(3,minmax(0,1fr))'));assert(!html.includes('mockup'));assert(!fs.readFileSync('site/saved.js','utf8').includes('demo'));assert(!css.includes('.mockup'));for(const path of ['site/saved.js','site/saved-comparison.js','site/saved-model.js'])assert(!fs.readFileSync(path,'utf8').includes('review-v1'));
  console.log(JSON.stringify({status:'passed',checks:['actual saved.js initialization from stored IDs and selections','actual open/close handlers preserve shortlist and return opener reference','actual selection handler rejects sixth and permits replacement','actual remove/Undo handlers preserve membership, selection and order','Undo toast is inside the active modal','temporary comparison preserves My School and existing peers','all selected schools receive equal chart lines from actual data','explicit reference alters differences without changing My School','refresh restores independent comparison and reference using original app restoreUrl','browser Back/Forward URL handlers reopen/close the temporary context without changing My School','Back restores prior view and filters','My School outside selection remains unchanged','My School included later in saved order remains unchanged','comparison grade/year filters do not alter explorer filters','actual Clear selection handler disables comparison and persists','actual fresh initialization restores persisted empty selection','malformed stored arrays fall back safely','actual cross-tab storage handler updates and clears shortlist','production storage event ignored','production starts empty without demo data','100-school save cap and duplicate protection','20 repeated remove/Undo cycles','balanced production HTML and mobile layout rules','no mockup labels, demos or review storage keys'],limitations:['DOM stub checks execute JavaScript logic only. They do not verify browser modal semantics, rendered charts, visual layouts or actual pointer/keyboard interaction.']},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
